/*
 * @author Carlos Burke - 1400681
 */
package GUI;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;
import java.io.FileWriter;
import java.io.IOException;

public class movieUpdate extends JFrame implements ActionListener {
    
    private Object[][] tmpInfo;
    private staffLawn sl;
    private int rw = 0;
    /**
     * Creates new form movieUpdae
     */
    public movieUpdate(Object[][] tmpInfoMovie, int rowSelect) {
        this.sl = sl;
        tmpInfo = tmpInfoMovie; 
        rw = rowSelect;
        initComponents();
        setWindowProperties();
        registerListeners();
    }

    private movieUpdate() {
        
    }
    
    public Object[][] showRec() {
        
        txtTitle.setText((String)tmpInfo[rw][0]); 
        txtGenre.setText((String)tmpInfo[rw][1]);
        txtDateReleased.setText((String)tmpInfo[rw][2]);
        txtRating.setText((String)tmpInfo[rw][3]);
        txtDateAquired.setText((String)tmpInfo[rw][4]); 
        txtRentalID.setText((String)tmpInfo[rw][5]);
        txtNoOfCopies.setText((String)tmpInfo[rw][6]);
        txtDailyCost.setText((String)tmpInfo[rw][7]); 
        
        return tmpInfo;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDateReleased = new javax.swing.JTextField();
        txtGenre = new javax.swing.JTextField();
        txtTitle = new javax.swing.JTextField();
        txtDateAquired = new javax.swing.JTextField();
        txtRentalID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        txtDailyCost = new javax.swing.JTextField();
        btnConfirm = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        txtNoOfCopies = new javax.swing.JTextField();
        txtRating = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("Date  Acquired:");

        jLabel4.setText("Rating:");

        jLabel7.setText("# of Copies:");

        jLabel6.setText("Rental ID:");

        jLabel2.setText("Genre:");

        jLabel8.setText("Daily Cost:");

        jLabel3.setText("Date Released:");

        btnCancel.setText("CANCEL");
        btnCancel.setToolTipText("");

        btnConfirm.setText("CONFIRM");

        lblTitle.setText("Title:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRating)
                            .addComponent(txtDateReleased)
                            .addComponent(txtTitle)
                            .addComponent(txtGenre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtDateAquired)
                                .addComponent(txtRentalID)
                                .addComponent(txtDailyCost, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNoOfCopies, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConfirm)
                .addGap(119, 119, 119))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTitle))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDateReleased, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDateAquired, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRentalID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNoOfCopies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDailyCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnConfirm))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setWindowProperties() {
        this.setSize(450,350);
        this.setVisible(true);
        this.setLocationRelativeTo(null); 
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.setResizable(false);       
    }
    
    private void registerListeners() {
        btnCancel.addActionListener(this);
        btnConfirm.addActionListener(this);        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtDailyCost;
    private javax.swing.JTextField txtDateAquired;
    private javax.swing.JTextField txtDateReleased;
    private javax.swing.JTextField txtGenre;
    private javax.swing.JTextField txtNoOfCopies;
    private javax.swing.JTextField txtRating;
    private javax.swing.JTextField txtRentalID;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource().equals(btnConfirm)) { 
              tmpInfo[rw][0] =  txtTitle.getText();
              tmpInfo[rw][1] =  txtGenre.getText();
              tmpInfo[rw][2] =  txtDateReleased.getText();
              tmpInfo[rw][3] =  txtRating.getText();              
              tmpInfo[rw][4] =  txtDateAquired.getText();
              tmpInfo[rw][5] =  txtRentalID.getText();
              tmpInfo[rw][6] =  txtNoOfCopies.getText();
              tmpInfo[rw][7] =  txtDailyCost.getText();               
              
            try {                
                FileWriter fp = new FileWriter("./DB/MovieRecords.txt");                
                    for(int count = 0; count < tmpInfo.length; count++) {                     
                        if (tmpInfo[count][0] == null)
                            break;                        
                            fp.write((String)tmpInfo[count][0] + " ");
                            fp.write((String)tmpInfo[count][1] + " ");
                            fp.write((String)tmpInfo[count][2] + " ");
                            fp.write((String)tmpInfo[count][3] + " ");
                            fp.write((String)tmpInfo[count][4] + " ");
                            fp.write((String)tmpInfo[count][5] + " ");
                            fp.write((String)tmpInfo[count][6] + " ");
                            fp.write((String)tmpInfo[count][7] + " \n");         
                        }
                            fp.close();
            } catch (IOException ex) { }
            staffLawn sll = new staffLawn();
             this.dispose();
             JOptionPane.showMessageDialog(rootPane, "Press the VIEW button to refresh table");
             sll.setEnabled(true);
        }
        
        if(e.getSource().equals(btnCancel)) {
            staffLawn mu = new staffLawn();            
            mu.setEnabled(true);
            this.dispose();            
        }
    }
}
